# Generated by Django 5.2.8 on 2025-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bjjpos',
            options={},
        ),
        migrations.AlterModelTable(
            name='bjjpos',
            table=None,
        ),
    ]
