# Generated by Django 5.2.8 on 2025-11-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posicoes', '0002_alter_bjjpos_options_alter_bjjpos_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bjjpos',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='bjjpos',
            table='posicoes',
        ),
    ]
